### ISSUE TITLE
`RuntimeSdkImageTests.VerifyImagesWithWebApps` test is failing in PR validation on `sdk:4.8-windowsservercore-ltsc2016` image

### ISSUE THREAD

**Issue by lbussell** [microsoft/dotnet-framework-docker#1117]
WindowsLtsc2016_amd64 4.8-windowsservercore-ltsc2016-runtime tests are failing consistently in PR validation. This isn't happening in the internal CI.

Link to failing PR validation run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=608811&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=b4a7524f-24ff-5cd3-3045-5ce9862a6c27

Test failure outputs (multiple across different tests):
```
System.InvalidOperationException : Failed to execute docker run --name webapp-133553521378571687 --rm  webapp-133553521378571687 powershell -command "dir ./bin/SimpleWebApplication.dll"
Exit code: 125
Standard Error: docker: Error response from daemon: container bed4570c99656a9e43c0f076450fcc1a9fd9826b45eb85f3a5e569fe1a61da74 encountered an error during hcsshim::System::Start: failure in a Windows system call: This operation returned because the timeout period expired. (0x5b4).
```

```
System.InvalidOperationException : Failed to execute docker build -t webapp-133553523877594066 --build-arg BASE_BUILD_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2016 -f D:\a_work\1\a\bin\Microsoft.DotNet.Framework.Docker.Tests\release\projects\webapp-4.8\Dockerfile D:\a_work\1\a\bin\Microsoft.DotNet.Framework.Docker.Tests\release\projects\webapp-4.8
Exit code: -1
Standard Error: The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; msbuild SimpleWebApplication.sln /p:Configuration=Release' returned a non-zero code: 4294967295: failed to shutdown container: container 51f610b096f674c819bd3642b8b8bd8b3dbb8f2f87c7843709dc939b3199096b encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The handle is invalid. (0x6)
```

**Comment by lbussell** [comment]
This is now failing to start the build stage with this awesome stack trace:

```
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=15.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=15.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.RuntimePropertyInfo.IsDefined(Type attributeType, Boolean inherit)
   at Microsoft.Internal.AttributeServices.IsAttributeDefined[T](ICustomAttributeProvider attributeProvider, Boolean inherit)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsExport(ICustomAttributeProvider attributeProvider)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExportMembers(Type type)+MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports()
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable()
   at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable(Type type, ICompositionElement origin)
   at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(String contractName)
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(ImportDefinition definition)
   at System.ComponentModel.Composition.Primitives.ComposablePartCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.DirectoryCatalog.<>c__DisplayClass36_0.<GetExports>b__0(ComposablePartCatalog catalog)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValues[T](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValues[T]()
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.get_Commands() in C:\image-builder\src\ImageBuilder.cs:line 38
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in C:\image-builder\src\ImageBuilder.cs:line 48
```

Regression is from https://github.com/microsoft/dotnet-framework-docker/pull/1182 where I mistakenly mis-classified the PR validation failure. This may require an issue filed in imagebuilder.

**Comment by mthalman** [comment]
Is the severity of this now different than the issue from before? The original issue only affected PR builds. Is the same true for this or will it affect the official internal build?

**Comment by lbussell** [comment]
> Is the severity of this now different than the issue from before? The original issue only affected PR builds. Is the same true for this or will it affect the official internal build?

I am running a test now to determine if it affects internal builds:

https://dev.azure.com/dnceng/internal/_build/results?buildId=2571931&view=results

**Comment by lbussell** [comment]
> This is now failing to start the build stage with this awesome stack trace:
> ...
> Regression is from [#1182](https://github.com/microsoft/dotnet-framework-docker/pull/1182) where I mistakenly mis-classified the PR validation failure. This may require an issue filed in imagebuilder.

This is not happening in https://github.com/microsoft/dotnet-framework-docker/pull/1185. It is back to the usual issue which is described in the issue body. Perhaps because the images were cached and not re-built? But they would have also been cached in https://github.com/microsoft/dotnet-framework-docker/pull/1184, so I'm not sure.

I also confirmed that this new issue does not affect internal builds as long as we have the VM image changes from #1185.
