### ISSUE TITLE
Build Tools 2015 fails to install on 4.7 image

### ISSUE THREAD

**Issue by ksmyth** [Microsoft/dotnet-framework-docker#23]
I am attempting to install the [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159) on the current 4.7 image, but it crashes.

    docker images
    REPOSITORY                    TAG                 IMAGE ID            CREATED      SIZE
    microsoft/dotnet-framework    4.7                 668d95076b9f        8 days ago      11.2 GB
    <snip>

    docker run -it --rm microsoft/dotnet-framework:4.7 cmd

    C:\>powershell "(new-object System.Net.WebClient).DownloadFile('https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe', 'BuildTools_Full.exe')"

    C:\>.\BuildTools_Full.exe  /NoRestart /Silent /Log BuildTools_Full.log

    C:\>type BuildTools_Full.log
    [0444:04D0][2017-06-22T15:04:40]i001: Burn v3.7.4029.0, Windows v10.0 (Build 14393:
    Service Pack 0), path: C:\BuildTools_Full.exe, cmdline: '/NoRestart /Silent /Log BuildTools_Full.log -burn.unelevated BurnPipe.{DDFC2EE7-21B7-4C30-B9B0-241ABFD2848C} {2404657F-2B37-4560-B3EC-A54E3A761DE7} 2036'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'RebootRequested' to value '0'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'ExecuteSecondaryInstaller' to value '0'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing string variable 'BundleProgressKey' to value 'Software\Microsoft\VisualStudio\14.0\Setup\BuildTools\Full'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing string variable 'SetupFeedKey' to value 'Software\Microsoft\VisualStudio\14.0\Setup\BuildTools\Full'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'LicenseFwlinkId' to value '614950'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'MoreLanguageFwlinkId' to value '558795'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'VSEIPAndPrivacyFwlinkId' to value '558769'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'MinOsLevelFwlinkId' to value '558783'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'SolutionFwlinkId' to value '558770'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'HelpFwlinkId' to value '558771'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'IE10FwlinkId' to value '558773'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'Win81BlockFwlinkId' to value '558774'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'SHA256BlockFwlinkId' to value '558781'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'Win81PreRelBlockFwlinkId' to value '558775'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'UninstallMddInfoFwlinkId' to value '558777'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'ThirdPartyHelpFwlinkId' to value '558778'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing numeric variable 'UpdateXmlFwlinkId' to value '558780'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing string variable 'NetfxProductVersion' to value '4.5.23026'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing string variable 'ProfessionalVSVersion' to value '11.0.50727'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing string variable 'ProductKey' to value '3NTMYRCPP3D7HMQMYJJKGJGWR'
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing string variable 'ProductSKU' to value ''
    [0444:04D0][2017-06-22T15:04:40]i000: Initializing string variable 'EditionDisplayName' to value 'Microsoft Build Tools 2015'
    [0444:04D0][2017-06-22T15:04:40]i000: Setting string variable 'WixBundleLog' to value 'C:\BuildTools_Full.log'
    [0444:04D0][2017-06-22T15:04:40]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\BuildTools_Full.exe'
    [0444:04D0][2017-06-22T15:04:40]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\'
    [0444:04D0][2017-06-22T15:04:41]i052: Condition '(VersionNT >= v6.1)' evaluates to true.
    [0444:04D0][2017-06-22T15:04:41]i000: Setting string variable 'WixBundleName' to value 'Microsoft Build Tools 2015'
    [0444:04D0][2017-06-22T15:04:41]i000: Loading managed bootstrapper application.
    [0444:04D0][2017-06-22T15:04:42]i000: Creating BA thread to run asynchronously.
    [0444:0788][2017-06-22T15:04:42]i000: Ux Started
    [0444:0788][2017-06-22T15:04:42]i000: MUX:  Loading LocalizableStrings.xml string from LocalizableStrings.xml
    [0444:0788][2017-06-22T15:04:42]i000: MUX:  Reset Result
    [0444:0788][2017-06-22T15:04:42]i000: MUX:  Current action: Install
    [0444:0788][2017-06-22T15:04:42]i000: Setting string variable 'CurrentOperation' to
    value 'Install'
    [0444:0788][2017-06-22T15:04:42]i000: Setting string variable 'IsLanguagePack' to value ''
    [0444:0788][2017-06-22T15:04:42]i000: MUX:  Current action: Install
    [0444:0788][2017-06-22T15:04:42]i000: Setting string variable 'CurrentOperation' to
    value 'Install'
    [0444:0788][2017-06-22T15:04:42]i000: MUX:  New last unconfirmed source: Web
    [0444:0788][2017-06-22T15:04:42]i000: MUX:  Source confirmed
    [0444:0788][2017-06-22T15:04:42]i000: Setting string variable 'CurrentRepairPackage' to value ''
    [0444:0788][2017-06-22T15:04:42]i000: Setting numeric variable 'UpdateInModify' to value 0
    [0444:0788][2017-06-22T15:04:42]i000: Setting numeric variable 'HypervisorSupported' to value 1
    [0444:0788][2017-06-22T15:04:42]i000: Setting numeric variable 'HypervisorEnabled' to value 1
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Resume = None
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Restart = Never
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Relation = None
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Action = Install
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Display = None
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'CustomInstallPath' to value 'C:\Program Files (x86)'
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'ExecuteSecondaryInstaller' to value '0'
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'SecondaryInstallerParameters' to value ''
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'SecondaryInstallerDynamicItems' to value ''
    [0444:0788][2017-06-22T15:04:43]i000: Setting numeric variable 'ConnectPipeToSecondaryInstaller' to value 0
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'SecondaryInstallerPipeName' to value ''
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'SecondaryInstallerPipeSecret' to value ''
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'RelationType' to value 'None'
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'DisplayMode' to value 'None'
    [0444:0788][2017-06-22T15:04:43]i000: Setting numeric variable 'NetworkAvailable' to value 1
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'OriginalDisplayMode'
    to value 'None'
    [0444:0788][2017-06-22T15:04:43]i000: Setting string variable 'OriginalDisplayModeSwitch' to value '/quiet'
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Metrics: ShouldSendData=True
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  SetupAction: Install
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  ProductVersion: 14.0.23107.10
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  ProductLanguage: 1033
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Branch: d14rel
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  OS: Windows Server 2016 Datacenter
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  OSVersion: 10.0.14393.0
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  OSLanguage: 1033
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  OSArchitecture: AMD64
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  RecordVirtualMachineInformation version: vrtual - 1
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  RecordVirtualMachineInformation serialNumber: 8535-9947-8418-2435-4874-1591-48
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Ux Initialized
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Aquiring mutex 'Global\BuildTools_Full_amd64_Mutex' with a timeout of 0 ms
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Mutex 'Global\BuildTools_Full_amd64_Mutex' ownership: True
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Seen existing cache mutex 'Global\BuildTools_Full_amd64_Mutex CacheMutex': False
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Aquiring mutex 'Global\BuildTools_Full_amd64_Mutex CacheMutex' with a timeout of 60000 ms
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Mutex 'Global\BuildTools_Full_amd64_Mutex CacheMutex' ownership: True
    [0444:0788][2017-06-22T15:04:43]e000: MUX:  ERROR: The type initializer for '<Module>' threw an exception.
    [0444:0788][2017-06-22T15:04:43]e000: MUX:  Stack:    at Microsoft.Devdiv.Bootstrapper.ManagedUx.RunSilentUI(ViewModelSilent viewModel)
       at Microsoft.Devdiv.Bootstrapper.ManagedUx.InternalRun()
       at Microsoft.Devdiv.Bootstrapper.ManagedUx.Run()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
    [0444:0788][2017-06-22T15:04:43]e000: MUX:  Exception: Info: InnerException: Info:
    [0444:0788][2017-06-22T15:04:43]e000: MUX:  ERROR: The C++ module failed to load during appdomain initialization.

    [0444:0788][2017-06-22T15:04:43]e000: MUX:  Stack:    at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
       at .cctor()
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Metrics: ShouldSendData=True
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Permission to upload: Yes
    [0444:0788][2017-06-22T15:04:43]i000: MUX:  Preparing to serialize data.
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Data serialized.
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Number of SQM File queued: 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  SQM sent: True
    [0444:0788][2017-06-22T15:04:44]i000: Setting string variable 'CEIPConsent' to value ''
    [0444:0788][2017-06-22T15:04:44]i000: Setting string variable 'SqmOption' to value ''
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: Configuration State
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  ----------------------------
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 426 = 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 8 = 31
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 596 = 5.0.0.0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 439 = BuildTools_Full_amd64
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 457 = 14.0.23107.10
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 440 = 14.0.23107
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 573 = d14rel
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 450 = 1033
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 15 = 2
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 16 = 198
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 1191 = 9
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 1193 = 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 1194 = 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 1189 = Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 3 = 1024
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 493 = 167784593
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 424 = 20119
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 453 = 10.0.14393.0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 13 = 1033
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 841 = 1
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 438 = 2
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 616 = 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 494 =
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 599 = 2
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 529 = False
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 833 = False
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 834 = False
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 563 = 000000000000
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 1063 = False
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 564 = False
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 439 = BuildTools_Full_amd64
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 457 = 14.0.23107.10
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 440 = 14.0.23107
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 437 = 1
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 461 =
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 517 = Crash: System.TypeInitialization
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 515 = 559b70de
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 501 = 449
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 642 = 37a
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 824 = 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 823 = 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Metrics: 434 = 0
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Watson Bucketting Parameters
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P1 - BuildTools_Full_amd64
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P2 - 14.0.23107.10
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P3 - 14.0.23107
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P4 - Install
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P5 -
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P6 - Crash: System.TypeInitialization
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P7 - 559b70de
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P8 - 449
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  P9 - 37a
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Adding Install Log to Watson=C:\BuildTools_Full.exe
    [0444:0788][2017-06-22T15:04:44]i000: MUX:  Adding Install Log to Watson=C:\BuildTools_Full.log

**Comment by ksmyth** [comment]
The 4.6.2 image seems to work fine.

**Comment by jflheureux** [comment]
I experience the same error on the microsoft/aspnet:4.7 image. microsoft/aspnet:4.6.2 works.

**Comment by kendrahavens** [comment]
@shirhatti Do you know what this might be?

**Comment by shirhatti** [comment]
Maybe @sujitnayak has a better idea?

**Comment by qasim9641** [comment]
Does anybody find the solution.I am not even able to install the build tools on 4.6.2 image?

**Comment by Skybladev2** [comment]
@qasim9641 I just copy `MSbuild` folder from my workstation + mount `Reference Assemblies` folders (x86 and x64) as they too big to copy.
Not an ideal, but it works for me.

**Comment by fredrikn** [comment]
I have the same problem. Can be a bug in Windows Server Core?! 
The following worked before, during February this year, but not anymore (maybe the core images is updated with some missing parts?!).

FROM microsoft/windowsservercore

SHELL ["powershell"]

# Install Microsoft Build Tools 2015
RUN Invoke-WebRequest "https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe" -OutFile "$env:TEMP\BuildTools_Full.exe" -UseBasicParsing 
RUN &  "$env:TEMP\BuildTools_Full.exe" /Silent /Full

**Comment by mahirsertkaya** [comment]
I have the same issue.

	[09F0:0AAC][2017-08-30T12:23:28]e000: MUX:  Exception: Info: InnerException: Info:
	[09F0:0AAC][2017-08-30T12:23:28]e000: MUX:  ERROR: The C++ module failed to load during appdomain initialization.

	[09F0:0AAC][2017-08-30T12:23:28]e000: MUX:  Stack:    at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )

**Comment by fredrikn** [comment]
I solved it after having the same problem.


I changed the windowsservercore from the latest image to an earlier tag.

Also the tools need to be installed before .Net 4.7


Here is my DockerFile that works:


FROM microsoft/windowsservercore:10.0.14393.1480

# Setup shell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Enable Features: ASP.NET, Web Application Development
RUN Add-WindowsFeature NET-Framework-45-ASPNET; \
    Add-WindowsFeature Web-Asp-Net45;

# Download vs_BuildTools.exe
RUN Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/11168600/e64d79b40219aea618ce2fe10ebd5f0d/vs_BuildTools.exe" -OutFile vs_BuildTools.exe

# Install MSBuild, Component.CoreBuildTools, and Component.Roslyn.Compiler
# Install Web.BuildTools.ComponentGroup

RUN Start-Process -FilePath ./vs_BuildTools.exe -NoNewWindow -Wait -ArgumentList '--quiet', '--wait', '--add Microsoft.VisualStudio.Workload.MSBuildTools', '--includeRecommended' ; \
Start-Process -FilePath ./vs_BuildTools.exe -NoNewWindow -Wait -ArgumentList '--quiet', '--wait', '--add Microsoft.VisualStudio.Workload.WebBuildTools', '--includeRecommended' ; \
rm ./vs_BuildTools.exe

# Add MSBuild to $PATH
RUN $env:PATH = 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\;' + $env:PATH; \
    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine);

# Install .NET 4.7
RUN powershell Invoke-WebRequest -Uri "https://download.microsoft.com/download/D/D/3/DD35CC25-6E9C-484B-A746-C5BE0C923290/NDP47-KB3186497-x86-x64-AllOS-ENU.exe" -OutFile NDP47-KB3186497-x86-x64-AllOS-ENU.exe; \
    .\NDP47-KB3186497-x86-x64-AllOS-ENU.exe /q;
RUN del .\NDP47-KB3186497-x86-x64-AllOS-ENU.exe


/Fredrik Normén


________________________________

**Comment by mahirsertkaya** [comment]
Thanks for that.
This microsoft/windowsservercore:10.0.14393.1480 image is definitely working because it has framework 3.5. While other more up-to-date images have framework 3.5 removed.

![image](https://user-images.githubusercontent.com/9527332/29873738-45d0b2ac-8d8c-11e7-9fa6-0278f29d141b.png)

**Comment by kendrahavens** [comment]
Thank you folks for posting workarounds! We are chatting internally about how to get fixed 4.7 images rolled out. Thank you for your patience.

**Comment by quickstar** [comment]
Is this bug with the current release 10.0.14393.1715 now fixed?

**Comment by mbadawi23** [comment]
I was able to get around this using the following line:
`RUN & "C:\temp\bin\BuildTools_Full.exe /Silent /Full | out-null";`

Apparently `Out-Null` blocks until `MSBuild` is installed.

Now this test returns `true` (I'm installing MSBuild 12):

`RUN & "Test-Path 'C:\Program Files (x86)\MSBuild\12.0\bin'";`

**Comment by MichaelSimons** [comment]
Do the recently added [microsoft/dotnet-framework-build](https://hub.docker.com/r/microsoft/dotnet-framework-build/) images solve the problem for you?  If not what additional components are needed?

**Comment by MichaelSimons** [comment]
Closing as there was no response to my previous question.  Assuming the new [microsoft/dotnet-framework-build](https://hub.docker.com/r/microsoft/dotnet-framework-build/) images are adequate.  If not feel free to open issues against the build images.
