### ISSUE TITLE
WCF test fails randomly with timeout

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#400]
The `VerifyWcfImagesWithApps` test case will occasionally timeout when attempting to access the service URL.

```
Starting test execution, please wait...
[xUnit.net 00:26:11.30]     Microsoft.DotNet.Framework.Docker.Tests.ImageTests.VerifyWcfImagesWithApps(imageDescriptor: ImageDescriptor { BuildVersion = null, OsVariant = "windowsservercore-ltsc2016", RuntimeVersion = "4.7" }) [FAIL]
  X Microsoft.DotNet.Framework.Docker.Tests.ImageTests.VerifyWcfImagesWithApps(imageDescriptor: ImageDescriptor { BuildVersion = null, OsVariant = "windowsservercore-ltsc2016", RuntimeVersion = "4.7" }) [26m 10s]
  Error Message:
   System.TimeoutException : Timed out attempting to access the endpoint http://192.168.163.169/Service1.svc on container wcf-132116635345085746
  Stack Trace:
     at Microsoft.DotNet.Framework.Docker.Tests.ImageTests.VerifyHttpResponseFromContainer(String containerName, String urlPath) in E:\A\_work\84\s\tests\Microsoft.DotNet.Framework.Docker.Tests\ImageTests.cs:line 317
   at Microsoft.DotNet.Framework.Docker.Tests.ImageTests.VerifyImages(ImageDescriptor imageDescriptor, IEnumerable`1 buildArgs, String appDescriptor, String runCommand, String testUrl) in E:\A\_work\84\s\tests\Microsoft.DotNet.Framework.Docker.Tests\ImageTests.cs:line 223
   at Microsoft.DotNet.Framework.Docker.Tests.ImageTests.VerifyWcfImages(ImageDescriptor imageDescriptor) in E:\A\_work\84\s\tests\Microsoft.DotNet.Framework.Docker.Tests\ImageTests.cs:line 197
  Standard Output Messages:
 Executing : docker pull dotnetdocker.azurecr.io/build-staging/325567/dotnet/framework/wcf:4.7-windowsservercore-ltsc2016
 4.7-windowsservercore-ltsc2016: Pulling from build-staging/325567/dotnet/framework/wcf
3889bb8d808b: Already exists
234c9b9e497c: Already exists
de31800ebd3a: Pulling fs layer
03cb089a4f85: Pulling fs layer
c58d200d53fb: Pulling fs layer
00037f2e23dd: Pulling fs layer
915faa000d12: Pulling fs layer
f548eefface1: Pulling fs layer
d9c4768d19ed: Pulling fs layer
fe918b868453: Pulling fs layer
915faa000d12: Waiting
baff8f6ec498: Pulling fs layer
00037f2e23dd: Waiting
d9c4768d19ed: Waiting
f548eefface1: Waiting
4a0e07e04b2c: Pulling fs layer
fe918b868453: Waiting
cd301e4e81eb: Pulling fs layer
baff8f6ec498: Waiting
4a0e07e04b2c: Waiting
7affc4f90213: Pulling fs layer
46fcff0db4c7: Pulling fs layer
cd301e4e81eb: Waiting
1f405f543f0a: Pulling fs layer
7affc4f90213: Waiting
46fcff0db4c7: Waiting
1f405f543f0a: Waiting
c58d200d53fb: Verifying Checksum
c58d200d53fb: Download complete
03cb089a4f85: Verifying Checksum
03cb089a4f85: Download complete
915faa000d12: Download complete
f548eefface1: Verifying Checksum
f548eefface1: Download complete
d9c4768d19ed: Verifying Checksum
d9c4768d19ed: Download complete
fe918b868453: Verifying Checksum
fe918b868453: Download complete
baff8f6ec498: Verifying Checksum
baff8f6ec498: Download complete
4a0e07e04b2c: Verifying Checksum
4a0e07e04b2c: Download complete
cd301e4e81eb: Verifying Checksum
cd301e4e81eb: Download complete
7affc4f90213: Verifying Checksum
7affc4f90213: Download complete
46fcff0db4c7: Download complete
1f405f543f0a: Verifying Checksum
1f405f543f0a: Download complete
de31800ebd3a: Verifying Checksum
de31800ebd3a: Download complete
00037f2e23dd: Verifying Checksum
00037f2e23dd: Download complete
de31800ebd3a: Pull complete
03cb089a4f85: Pull complete
c58d200d53fb: Pull complete
00037f2e23dd: Pull complete
915faa000d12: Pull complete
f548eefface1: Pull complete
d9c4768d19ed: Pull complete
fe918b868453: Pull complete
baff8f6ec498: Pull complete
4a0e07e04b2c: Pull complete
cd301e4e81eb: Pull complete
7affc4f90213: Pull complete
46fcff0db4c7: Pull complete
1f405f543f0a: Pull complete
Digest: sha256:48e3dcfca0033dcad0544ab483fc7513b9ab80be6ecc460ff4a37487075a7505
Status: Downloaded newer image for dotnetdocker.azurecr.io/build-staging/325567/dotnet/framework/wcf:4.7-windowsservercore-ltsc2016

 Executing : docker build -t wcf-132116635345085746  --build-arg BASE_WCF_IMAGE=dotnetdocker.azurecr.io/build-staging/325567/dotnet/framework/wcf:4.7-windowsservercore-ltsc2016 -f E:\A\_work\84\s\tests\Microsoft.DotNet.Framework.Docker.Tests\bin\Release\netcoreapp2.1\projects\wcf-4.7\Dockerfile E:\A\_work\84\s\tests\Microsoft.DotNet.Framework.Docker.Tests\bin\Release\netcoreapp2.1\projects\wcf-4.7
 Sending build context to Docker daemon   7.68kB

 Step 1/8 : ARG BASE_WCF_IMAGE
Step 2/8 : FROM $BASE_WCF_IMAGE AS runtime
 ---> f4edcf91815a
Step 3/8 : WORKDIR /inetpub/wwwroot
 ---> Running in a3f97e2f72a1
Removing intermediate container a3f97e2f72a1
 ---> a499de94d07b
Step 4/8 : COPY web.config .
 ---> cc67cc3e4193
Step 5/8 : COPY Service1.svc .
 ---> 0487a5c2ba9b
Step 6/8 : WORKDIR /inetpub/wwwroot/App_Code
 ---> Running in 33ce38a44f4b
Removing intermediate container 33ce38a44f4b
 ---> 0f76bd4a7ebd
Step 7/8 : COPY IService1.cs .
 ---> 46037beec4ab
Step 8/8 : COPY Service1.svc.cs .
 ---> 6e57eb615886
Successfully built 6e57eb615886
Successfully tagged wcf-132116635345085746:latest

 Executing : docker run --rm -d --name wcf-132116635345085746 wcf-132116635345085746 
 9c5e30e4fa6e7116e0f4f266f7f07aa2e0c7d13972b549e667dc58ec8cdc552f

 Executing : docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" wcf-132116635345085746
 192.168.163.169

 Request to http://192.168.163.169/Service1.svc failed - retrying: System.AggregateException: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at Microsoft.DotNet.Framework.Docker.Tests.ImageTests.VerifyHttpResponseFromContainer(String containerName, String urlPath) in E:\A\_work\84\s\tests\Microsoft.DotNet.Framework.Docker.Tests\ImageTests.cs:line 289
 ---> (Inner Exception #0) System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
    at System.Threading.Tasks.ValueTask`1.get_Result()
    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)<---
```

**Comment by mthalman** [comment]
Same issue occurs with the ASP.NET `VerifyAspnetImagesWithApps` test:
```
Request to http://192.168.174.137/hello-world.aspx failed - retrying: System.AggregateException: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.DotNet.Framework.Docker.Tests.ImageTests.VerifyHttpResponseFromContainer(String containerName, String urlPath) in E:\A\_work\76\s\tests\Microsoft.DotNet.Framework.Docker.Tests\ImageTests.cs:line 289
---> (Inner Exception #0) System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by MichaelSimons** [comment]
Closing this as we haven't seen the tests fail recently.
