### ISSUE TITLE
core/aspnet:3.0-alpine has no tzdata, TimeZoneInfo does not work

### ISSUE THREAD

**Issue by hn3000** [microsoft/dotnet-framework-docker#436]
In an application running on core/aspnet:3.0-alpine 
(`mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine`), 
the following `TimeZoneInfo` call fails:

```
TimeZoneBerlin = TimeZoneInfo.FindSystemTimeZoneById("Europe/Berlin");
```

The stacktrace tells us that `/usr/share/zoneinfo/Europe/Berlin` does not exist.

Installing `tzdata` with `RUN apk add tzdata` in `Dockerfile` solves the problem, 
but should the image not come with tzdata pre-installed? 

Without tzdata, this core dotnet feature does not work.

Stacktrace:
```
www-local | xyz.WebApp Error: 0 : Failed to launch UpdateLicenseDayLogTask. Ex: System.AggregateException: One or more errors occurred. (The type initializer for 'xyz.Xyz.DateTimeExtension' threw an exception.)
www-local |  ---> System.TypeInitializationException: The type initializer for 'xyz.Xyz.DateTimeExtension' threw an exception.
www-local |  ---> System.TimeZoneNotFoundException: The time zone ID 'Europe/Berlin' was not found on the local computer.
www-local |  ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/share/zoneinfo/Europe/Berlin'.
www-local |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
www-local |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
www-local |    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
www-local |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
www-local |    at Internal.IO.File.ReadAllBytes(String path)
www-local |    at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(String id, TimeZoneInfo& value, Exception& e)
www-local |    --- End of inner exception stack trace ---
www-local |    at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
```

**Comment by MichaelSimons** [comment]
@hn3000 - FYI, all issues related to the .NET Core Docker images should get logged at https://github.com/dotnet/dotnet-docker/issues.

The exclusion of tzdata is by design.  For details please read [this recent announcement](https://github.com/dotnet/dotnet-docker/issues/1366).
