### ISSUE TITLE
XamlReader.Load failed with Win32Exception 'The specified module could not be found'

### ISSUE THREAD

**Issue by benlaan** [Microsoft/dotnet-framework-docker#96]
I have a 32bit console app that loads a XAML-based configuration file at startup. The error below implies that the DLL cannot be found, however it is present at the path below.

Any idea what I might be doing wrong?

### Dockerfile

```
FROM microsoft/dotnet-framework
COPY .\app .\app
CMD ["powershell", "app\app.exe"]

```
### Exception

Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load during appdomain initialization.
 ---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: The specified module could not be found
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: The specified module could not be found
  --- End of inner exception stack trace ---
  at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
  at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
  at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
  at ?A0x4676cc04.CreateCModuleInitialize()
  at ?A0x4676cc04.??__E?A0x4676cc04@cmiStartupRunner@@YMXXZ()
  at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
  at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
  at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
  at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
  --- End of inner exception stack trace ---
  at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
  at .cctor()
  --- End of inner exception stack trace ---
  at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
  at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
  at System.Windows.Markup.XamlReader.Load(Stream stream)

**Comment by benlaan** [comment]
I fixed this issue by taking the latest version of the dotnet-framework image

Nothing to see here..
